datasets:
- max_samples: 1000
  name: sample_dataset
  path: ./data/samples.jsonl
  source: local
  test_split: 0.2
  validation_split: 0.1
description: Template configuration for cybersecurity benchmarking
evaluation:
  batch_size: ${EVAL_BATCH_SIZE:16}
  enable_detailed_logging: ${ENABLE_DEBUG_LOGS:false}
  metrics: ${EVAL_METRICS:accuracy,precision,recall,f1_score}
  parallel_jobs: ${EVAL_PARALLEL_JOBS:2}
  timeout_minutes: ${EVAL_TIMEOUT:30}
models:
- config:
    api_key: ${OPENAI_API_KEY:test_key}
  max_tokens: ${MODEL_MAX_TOKENS:512}
  name: gpt-3.5-turbo
  path: gpt-3.5-turbo
  temperature: 0.1
  type: openai_api
- config:
    api_key: ${ANTHROPIC_API_KEY}
  max_tokens: ${MODEL_MAX_TOKENS:1024}
  name: claude-3-haiku
  path: claude-3-haiku-20240307
  temperature: 0.1
  type: anthropic_api
name: Default Cybersecurity Experiment
output_dir: ./results
