name: "Demo CLI Configuration"
description: "Demonstration configuration for CLI testing"
output_dir: "./results/demo"

datasets:
  - name: "cybersecurity_samples"
    source: "local"
    path: "./data/cybersec_samples.jsonl"
    max_samples: 500
    test_split: 0.2
    validation_split: 0.1

models:
  - name: "gpt-3.5-turbo"
    type: "openai_api"
    path: "gpt-3.5-turbo"
    config:
      api_key: "${OPENAI_API_KEY}"
    max_tokens: 1024
    temperature: 0.1

  - name: "claude-3-haiku"
    type: "anthropic_api"
    path: "claude-3-haiku-20240307"
    config:
      api_key: "${ANTHROPIC_API_KEY}"
    max_tokens: 1024
    temperature: 0.1

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score"]
  parallel_jobs: 4
  timeout_minutes: 30
  batch_size: 32
  enable_detailed_logging: true
